// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: service/content/proto/content/contents.proto

package contents

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Contents service

func NewContentsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Contents service

type ContentsService interface {
	Save(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type contentsService struct {
	c    client.Client
	name string
}

func NewContentsService(name string, c client.Client) ContentsService {
	return &contentsService{
		c:    c,
		name: name,
	}
}

func (c *contentsService) Save(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Contents.Save", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Contents service

type ContentsHandler interface {
	Save(context.Context, *Request, *Response) error
}

func RegisterContentsHandler(s server.Server, hdlr ContentsHandler, opts ...server.HandlerOption) error {
	type contents interface {
		Save(ctx context.Context, in *Request, out *Response) error
	}
	type Contents struct {
		contents
	}
	h := &contentsHandler{hdlr}
	return s.Handle(s.NewHandler(&Contents{h}, opts...))
}

type contentsHandler struct {
	ContentsHandler
}

func (h *contentsHandler) Save(ctx context.Context, in *Request, out *Response) error {
	return h.ContentsHandler.Save(ctx, in, out)
}
